
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - pipelines/*
    - test/*
    - README.md
    - .dockerignore
    - .gitignore

variables:
- name: appName
  value: 'ScanApp'
- name: tag
  value: '$(Build.BuildId)' 


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: Create application image
  inputs:
    targetType: 'inline'
    script: |
            docker build -t  ${{ lower(variables.appName) }}:$(tag) .
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Bash@3
  displayName: Check vulnerabilities
  inputs:
    targetType: 'inline'
    script: |
      docker run --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        sysdiglabs/secure-inline-scan:2 \
        --sysdig-url $(SYSDIG_URL) \
        --sysdig-token $(SYSDIG_API_TOKEN) \
        --storage-type docker-daemon \
        --storage-path /var/run/docker.sock \
        ${{ lower(variables.appName) }}:$(tag)      

